import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import { Footer, Header, Sidebar } from '@/components/layout'
import { ThemeProvider } from '@/components/theme-provider'

import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Website Layout w/ Sidebar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={fontSans.variable}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <div className='mx-auto flex w-full max-w-screen-xl flex-1 flex-row'>
            <Sidebar />
            <main className='flex w-full flex-col p-5'>{children}</main>
          </div>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
